version: '2'

services:

    grafana:
        image: tianon/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        environment:
            GF_USERS_ALLOW_SIGN_UP: 'false'
        #ports:
        #    - 3000:3000

    prom:
        # https://github.com/prometheus/prometheus/releases
        image: prom/prometheus:v1.6.1
        container_name: prom
        hostname: prom
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        mem_limit: 150m
        command: [
            '-config.file=/etc/prometheus/prometheus.yml',
            '-storage.local.path=/prometheus',
            '-web.console.libraries=/usr/share/prometheus/console_libraries',
            '-web.console.templates=/usr/share/prometheus/consoles',
            # As a rule of thumb, you should have at least 50% headroom in physical memory over the configured heap size. 
            '-storage.local.target-heap-size=100000000',
        ]

    node-exporter:
        # https://github.com/prometheus/node_exporter/releases
        image: prom/node-exporter:v0.14.0
        container_name: prom-node-exporter
        hostname: node-exporter
        restart: always
        volumes:
            - /:/rootfs:ro
        # https://github.com/prometheus/node_exporter/issues/66#issuecomment-197300231
        command: [
            '-collector.procfs', '/rootfs/proc',
            '-collector.sysfs', '/rootfs/sys',
            '-collector.filesystem.ignored-mount-points', '^/((rootfs/)?(sys|proc|dev|var/lib/nfs|var/lib/docker|run/docker)|host|etc|opt/node-exporter/data)($$|/)|^/$$|/\.gvfs$$',
        ]

    cadvisor:
        # https://github.com/google/cadvisor/releases
        image: google/cadvisor:v0.24.1
        # https://github.com/google/cadvisor/issues/1556 (v0.25.0 is no good)
        container_name: prom-cadvisor
        hostname: cadvisor
        restart: always
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /var/log/:/var/log:ro

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br-prometheus
